theme: jekyll-theme-time-machine

# Site settings

title: 夏
SEOTitle: 夏的博客 | ats' Blog
header-img: img/home-bg-hill.jpg
email: jimboyeah@gmail.com
description: "记录"
keyword: "夏, ats"
url: "https://jimboyeah.github.io"
baseurl: ""
